receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed # Optional: "basic" or "detailed"

  zipkin:
    # endpoint: "http://zipkin:9411/api/v2/spans"
    endpoint: "http://host.docker.internal:9411/api/v2/spans"

  elasticsearch:
    # endpoints: ["http://opensearch:9200"]
    # endpoints: ["http://host.docker.internal:9200"]
    endpoint: http://host.docker.internal:9200
    tls:
      insecure: true

  # opensearch is unmaintained 2025/04/13
  opensearch/log:
    # logs_index: "otel-v1-apm-span-{% raw %}{{ .yyyy.MM.dd }}{% endraw %}"
    http:
      endpoint: http://host.docker.internal:9200
      tls:
        insecure: true

  # opensearch/trace:
  #   # logs_index: "otel-traces-{% raw %}{{ .yyyy.MM.dd }}{% endraw %}"
  #   http:
  #     endpoint: http://host.docker.internal:9200
  #     tls:
  #       insecure: true

  # otlp/data-prepper:
  #   endpoint: localhost:9200
  #   tls:
  #     insecure: true

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

  otlp/data-prepper:
    endpoint: "http://host.docker.internal:21890"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [zipkin, debug, opensearch/trace]
      exporters: [zipkin, debug, otlp/data-prepper]

    metrics:
      receivers: [otlp]
      processors: [batch]
      # exporters: [prometheusremotewrite, debug]
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      # exporters: [opensearch/log, debug]
      exporters: [opensearch/log, debug]
