simple-sample-pipeline:
  workers: 2
  delay: 5000
  source:
    random:
  buffer:
    bounded_blocking:
      buffer_size: 1024
      batch_size: 256
  processor:
    - string_converter:
        upper_case: true
  sink:
    - stdout:
